FROM node:20-alpine AS builder

WORKDIR /app

COPY web/frontend/package*.json ./
RUN npm ci

COPY web/frontend/ .

ARG API_URL=http://127.0.0.1:5000
ENV API_URL=$API_URL

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["npm", "start"]
